### ISSUE TITLE
Example broken?

### ISSUE THREAD

**Issue by caco3** [Nicoretti/crc#10]
I tried to run the example `Create a custom crc configuration for the crc calculation` in the readme.
How ever It showed following error on Python 3.8.10:
```
Traceback (most recent call last):
  File "crctest.py", line 15, in <module>
    crc_calculator = CrcCalculator(configuration, use_table)
  File "/usr/local/lib/python3.8/dist-packages/crc.py", line 332, in __init__
    self._crc_register = TableBasedCrcRegister(configuration)
  File "/usr/local/lib/python3.8/dist-packages/crc.py", line 230, in __init__
    super().__init__(configuration)
  File "/usr/local/lib/python3.8/dist-packages/crc.py", line 104, in __init__
    self._register = configuration.init_value & self._bitmask
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'
```

The solution was to changed all configs from tuples to normal values by removing all appended commas:
```
width = 8
poly=0x07
init_value=0x00
final_xor_value=0x00
reverse_input=False
reverse_output=False
```

The check failed afterwards, however it works correctly for the different Poly (0xE7) .
Tested with following patterns:

- `data = [0x12]`
- `data = [0xFF]`
- `data = [0x34, 0x12]`
- `data = [0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde]`

**Comment by Nicoretti** [comment]
Hi @caco3,

thx for reporting the issue!

Seems about right. I think it was a copy & paste issue/error,  when I created the examples. 
Regarding the failing check: 
`at first glance it looks like that I also did not update the expected crc for each of the examples`

I'll fix tuple/comma issue in the examples and also will recheck and fix the expected checksums.

best
Nico

**Comment by caco3** [comment]
👍
