### ISSUE TITLE
Invalid checksum for HDLC Frame 

### ISSUE THREAD

**Issue by FranckN-maker** [Nicoretti/crc#112]
## CONTEXT :

Using GNURADIO I saved AIS vessel information in file Radio reception. Using Python code I look for the preamble and start signal. so after bit destuffing, I try to check the FCS with a crc16 calculation.

## ISSUE :

The data from the AIS recorded (HDLC)
```python
'0x124174d2160000f5791afa2c302987f07fa57b0060'
# or
'0x120x410x740xd20x160x000x000xf50x790x1a0xfa0x2c0x300x290x870xf00x7f0xa50x7b0x000x60'
# or 
'0x12 0x41 0x74 0xd2 0x16 0x00 0x00 0xf5 0x79 0x1a 0xfa 0x2c 0x30 0x29 0x87 0xf0 0x7f 0xa5 0x7b 0x00 0x60'
```

The CRC(from FCS part of HDLC)
```python
'0x1b18'
```

those data works fine under this application : http://www.sunshine2k.de/coding/javascript/crc/crc_js.html

note : The application uses this format : 0x12 0x41 0x74 0xd2 0x16 0x00 0x00 0xf5 0x79 0x1a 0xfa 0x2c 0x30 0x29 0x87 0xf0 0x7f 0xa5 0x7b 0x00 0x60 

![fichier_site_crc](https://github.com/Nicoretti/crc/assets/127703280/e1be67c0-1e3a-4f47-85e4-635d9834de18)

MAYBE

in your example you used bytes([1,2,3,4,5]) --> those bytes function return  b'\x01\x02\x03\x04\x05'

but if you use value above 9 you have strange characters (as if ASCII transcription was done).

for example if I use :

'124174d2160000f5791afa2c302987f07fa57b0060'

And a byte.fromhex('124174d2160000f5791afa2c302987f07fa57b0060')

b'\x12At\xd2\x16\x00\x00\xf5y\x1a\xfa,0)\x87\xf0\x7f\xa5{\x00`'  

the character are strange and of course the value from verify is False..

CONFIGURATION 

SYSTEM : 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Python : 3.11.4 

Thank you for your help

**Comment by Nicoretti** [comment]
Hi @FranckN-maker,

thanks for reporting. Apparently the snippet below works just fine.

```python
from crc import Configuration, Register

config = Configuration(
    width=16,
    polynomial =0x1021,
    init_value=0xffff,
    final_xor_value=0xffff,
    reverse_input=False,
    reverse_output=False,
)

reg = Register(config)

expected = 0x1B18
data = [18, 65, 116, 210, 22, 0, 0, 245, 121, 26, 250, 44, 48, 41, 135, 240, 127, 165, 123, 0, 96]

reg.init()
reg.update(data)

assert expected == reg.digest()
```

That said, it looks like you have found a bug in the convenience wrapper `Calculator`.

```python
from crc import Configuration, Calculator

config = Configuration(
    width=16,
    polynomial =0x1021,
    init_value=0xffff,
    final_xor_value=0xffff,
    reverse_input=False,
    reverse_output=False,
)

calc = Calculator(config)

expected = 0x1B18
data = [18, 65, 116, 210, 22, 0, 0, 245, 121, 26, 250, 44, 48, 41, 135, 240, 127, 165, 123, 0, 96]

assert expected == calculator.checksum(data)
```
yields the wrong checksum.

## Recommendation
Until  #113 have been fixed, I recommend you use the register API (`TablesBasedRegister`, `Register`).

best
Nico

**Comment by Nicoretti** [comment]
Issue is closed, because the underlying problem is now tracked in #113.
If the provided recommendation is not sufficient or not leading to a resolution, please reopen the issue.
