### ISSUE TITLE
🐞 Invalid checksum is calculated when using `Calculator` instead of `Register` classes

### ISSUE THREAD

**Issue by Nicoretti** [Nicoretti/crc#113]
# Summary
While the exact same configuration yield a valid crc checksum when using the primitives of the library directly, 
using the `Calculator` class yields a wrong result.

## Reproducing the Issue

Reproducibility: <pick one of> sporadic, regularly, always

```python
from crc import Configuration, Calculator

config = Configuration(
    width=16,
    polynomial =0x1021,
    init_value=0xffff,
    final_xor_value=0xffff,
    reverse_input=False,
    reverse_output=False,
)

calc = Calculator(config)

expected = 0x1B18
data = [18, 65, 116, 210, 22, 0, 0, 245, 121, 26, 250, 44, 48, 41, 135, 240, 127, 165, 123, 0, 96]

assert expected == calculator.checksum(data)
```

## Expected Behaviour
The resulting checksum is `0x1B18`

## Actual Behaviour
The resulting checksum is `0x356c`

## Root Cause (optional)
?

## Context
The following snippet generates the correct checksum:
```python
from crc import Configuration, Register

config = Configuration(
    width=16,
    polynomial =0x1021,
    init_value=0xffff,
    final_xor_value=0xffff,
    reverse_input=False,
    reverse_output=False,
)

reg = Register(config)

expected = 0x1B18
data = [18, 65, 116, 210, 22, 0, 0, 245, 121, 26, 250, 44, 48, 41, 135, 240, 127, 165, 123, 0, 96]

reg.init()
reg.update(data)

assert expected == reg.digest()
```

### System

 - Package Version 4.3.0

#### Related Issues (optional)
* #112

**Comment by gertvdijk** [comment]
I think I have found the problem on this one.

1. The input data is of type list[int] (= Iterable).
2. The `_bytes_generator` will then call `bytes(e)` for each element.
3. Running `bytes(18)` does not yield a bytestring with character 18, but a bytestring of 18 NULLs.
    ```
    >>> bytes(18)
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    ```
5. What is going into the register is not the data, but just a whole bunch of `\x00`s.

To work around the problem, wrap it in a bytearray like this:

```diff
- assert expected == calculator.checksum(data)
+ assert expected == calculator.checksum(bytearray(data))
```

The actual fix should be done in the `_bytes_generator` (only called from the Calculator).

```python
    elif isinstance(data, (Iterable, BinaryIO)):
        yield from (bytes(e) for e in data)
```

What gave me the hint was using pdb, setting `breakpoint()` and running `locals()` in the debugger after creating a test case `test_calculator_with_custom_config`.

```
$ pytest -k test_calculator_with_custom_config
=== test session starts ===
platform linux -- Python 3.8.17, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/gert/repos/crc
collected 46 items / 45 deselected / 1 selected                                                                                                                             

test/unit/test_crc.py 
>>>> PDB set_trace (IO-capturing turned off) >>>
> /home/gert/repos/crc/src/crc/_crc.py(396)checksum()
-> self._crc_register.update(chunk)
(Pdb) l
391                 Checksum for the given input data.
392             """
393             self._crc_register.init()
394             for chunk in _bytes_generator(data):
395                 breakpoint()
396  ->             self._crc_register.update(chunk)
397             return self._crc_register.digest()
398  
399         def verify(self, data: InputType, expected: int) -> bool:
400             """
401             Verifies that the checksum for the given data is the expected one.
(Pdb) locals()
{'self': <crc._crc.Calculator object at 0x7f009450b760>, 'data': [18, 65, 116, 210, 22, 0, 0, 245, 121, 26, 250, 44, 48, 41, 135, 240, 127, 165, 123, 0, 96], 'chunk': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
```

**Comment by Nicoretti** [comment]
I have investigated the issue and I from my point of view the test/error scenario is not correct.
According to the API `List[int]` is not supported (see `InputType`). So imho this is not a bug rather a potential feature.

If I recall it correctly, I did not add support for `List[int]` to keep the input more "type safe".  Because for integers where `size > 1 byte` it is unclear how to interpret them ([endianness](https://en.wikipedia.org/wiki/Endianness)). Therefore I wanted the user to make sure he/she/it/* is passing bytes. The possibility to pass a single `int` was just added for convenience and also assumes it is only a single byte `int`.

@FranckN-maker, @gertvdijk any thoughts on this?

**Comment by gertvdijk** [comment]
Agree, `list[int]` is unsupported as of right now.

**Comment by FranckN-maker** [comment]
hi, I make this code using your example :+1: 

config = Configuration(
    width=16,
    polynomial =0x1021,
    init_value=0xffff,
    final_xor_value=0xffff,
    reverse_input=False,
    reverse_output=False,
)

reg = Register(config)

expected = HexaCRCin #0x1B18
data = [int(l) for l in DataWthoutCRCHex_2]
recData = numpy.asarray(data)
reg.init()
reg.update(bytearray(data))

assert expected == reg.digest()
print(f'CRCCheck OK :{expected == reg.digest()}')

now it works, and only bytes seems to be OK, I tried list of int, but  I get issue.
thank you.

**Comment by Nicoretti** [comment]
Hi @FranckN-maker,

perfect, I'll close this ticket then. Also the code below also should work fine for you.

```python
from crc import Configuration, Calculator

config = Configuration(
    width=16,
    polynomial =0x1021,
    init_value=0xffff,
    final_xor_value=0xffff,
    reverse_input=False,
    reverse_output=False,
)
calc = Calculator(config)

expected = HexaCRCin #0x1B18
data = [int(l) for l in DataWthoutCRCHex_2]
recData = numpy.asarray(data)
data_as_bytes = bytearray(data)

assert expected == calc.checksum(data_as_bytes)
print(f'CRCCheck OK :{expected == calc.checksum(data_as_bytes)}')
```

**Comment by FranckN-maker** [comment]
thank you for all.

**Comment by Nicoretti** [comment]
@FranckN-maker you are welcome.

**Comment by baryluk** [comment]
We also found similar issue when updating crc from around 1.3, to newer versions.

https://github.com/baryluk/fnirsi-usb-power-data-logger/issues/12#issuecomment-1548455198 and comments later. (you can ignore earlier comments as they are about update from 1.2 to 1.3, which was easy to handle)

Could you please reopen this bug, and make `checksum` assert a type of its arguments on entry, so it is trivial to fix and find?

**Comment by gertvdijk** [comment]
@baryluk 

> Could you please reopen this bug, and make `checksum` assert a type of its arguments on entry, so it is trivial to fix and find?

My opinion is that typing errors should be caught by type checkers and version 5 of `crc` includes the annotations for this to show the error for you.
