### ISSUE TITLE
Crc8.SAEJ1850 has wrong `init_value` and `final_xor_value`

### ISSUE THREAD

**Issue by bks-nist** [Nicoretti/crc#127]
`Crc8.SAEJ1850` should have `init_value=0xff` and `final_xor_value=0xff`. 

[SAE J1850-2001](https://law.resource.org/pub/us/cfr/ibr/005/sae.j1850.2001.pdf) says "7.4.1 [...] a. The CRC calculation [...] shall be initially set to the 'all ones' state [...]" and "e. The CRC byte is made equal to [...] the ones complement of R(X)," i.e. XOR with `0xFF`.

This also matches the configuration used in [crc-rs](https://docs.rs/crate/crc/latest).

**Comment by Nicoretti** [comment]
Hi @bks-nist,

Thanks for reporting! :+1: 
I'll be updating the library and creating a new release with the fix in the next few days.

best
Nico

**Comment by Nicoretti** [comment]
Just released [crc 6.0.0](https://pypi.org/project/crc/6.0.0/)
