### ISSUE TITLE
📚 Readme update

### ISSUE THREAD

**Issue by Ramya-Ab** [Nicoretti/crc#140]
# Summary

The "Available CRC Configurations" section of the readme is to be updated, with respect to the attribute "SAJ1850"

# Details

Under the "Available CRC Configurations" section of the readme:

1. Under CRC8, there is an attribute named "SAJ1850". However, using this attribute for CRC calculation causes an `AttributeError: SAJ1850`. Using the attribute "SAEJ1850" works, however. So the documentation can be updated to mention "SAEJ1850" instead of "SAJ1850".

2. The section also states "For convince various frequently used crc configurations ship with the library out of the box." - is it meant to state "For convenience" instead? If yes, this typo can be corrected.

## Background & Context

Why should this documentation be added/updated?
Using the attribute "SAJ1850" instead of "SAEJ1850" for CRC calculation causes an `AttributeError: SAJ1850`.
Possible typo in the documentation: "For convince various frequently used crc configurations ship with the library out of the box." - is it meant to state "For convenience" instead?

## References

https://nicoretti.github.io/crc

# Task(s)

- [ ] Update readme: Change "SAJ1850" to "SAEJ1850"
- [ ] Update readme: Correct possible typo of "convince" to "convenience"

Thanks!

**Comment by regulusarcturusblack** [comment]
I've created a pull request #141 for this - please check. Thanks!

**Comment by Nicoretti** [comment]
Hi @Ramya-Ab,

thanks for reporting the issue and providing a fix 👍.

best
Nico
