### ISSUE TITLE
Inconsistent CRC result for different input type

### ISSUE THREAD

**Issue by noonchen-ni** [Nicoretti/crc#162]
I am currently using the latest release of this module `crc-7.0.0`.

The result is wrong when the input data is a list of int:
```
>>> from crc import Calculator, Crc32
>>>
>>> d1 = 35
>>> d2 = [35]
>>> d3 = bytes([35])
>>>
>>> calc = Calculator(Crc32.CRC32)
>>>
>>> calc.checksum(d1)
1885708031
>>> calc.checksum(d2)
167270199
>>> calc.checksum(d3)
1885708031
>>>
```

**Comment by gertvdijk** [comment]
I believe it's the same case as https://github.com/Nicoretti/crc/issues/113#issuecomment-1742049589.
And your type checker should warn you that your input type `list[int]` is unsupported.

**Comment by noonchen-ni** [comment]
AFAIK, vscode doesn't show any warning when I pass a list[int] to `checksum` method.

**Comment by gertvdijk** [comment]
Just double checked it quickly: it does, both mypy and Pylance provide this error for you. Please check your type checker configuration.
![image](https://github.com/Nicoretti/crc/assets/1550527/3877dd7c-f242-4758-8456-c3b5a68c006c)

Also, I think it should be 

```diff
-calc = Calculator(Crc32.CRC32)
+calc = Calculator(Crc32.CRC32.value)
```

**Comment by noonchen-ni** [comment]
Well, my concerns are solved, you can close this issue if you wish, Thanks!

**Comment by gertvdijk** [comment]
> I am using the default setting of pylance in vscode, and here is my screenshot:

Looks like you have some broader issues with Pylance in your VS Code setup then. Check basic things like: correct Python interpreter set up in VS Code? Type something obviously wrong; does it warn you at all? E.g. `print(1234 + "foo")`

![image](https://github.com/Nicoretti/crc/assets/1550527/b45714ce-7e90-4cba-8e90-cc2a90f305a8)

If I have an invalid Python interpreter selected it will be silent as in your screenshot.

![image](https://github.com/Nicoretti/crc/assets/1550527/759d3d9e-71f4-4ada-ae3e-b254868a9723)

**Comment by Nicoretti** [comment]
@gertvdijk thanks for taking care of this. @noonchen-ni as discussed the issue will be closed. 
For further details see also : https://github.com/Nicoretti/crc/issues/113#issuecomment-1742049589
