### ISSUE TITLE
📝Performance issue

### ISSUE THREAD

**Issue by mvkonovalov** [Nicoretti/crc#182]
Hello, 

I have tried to use the module and found extremal performance penalty during calculation of CRC32 with [`TableBasedRegister`](https://nicoretti.github.io/crc/#__tabbed_5_2) of chunked data of large file. Bellow you can find test to reproduce issue.

```python
#!/usr/bin/env python3

import argparse
import crc
import sys
import fastcrc
import perftester as pt
import os

MAX_BUFFER_SIZE = 64 * 1024
MAX_FILE_SIZE = 1024*1024

def test_fastcrc(file_size):
    crc32 = 0

    with open('test.bin', 'rb') as f:
        while file_size:
            if file_size > MAX_BUFFER_SIZE:
                receive_size = MAX_BUFFER_SIZE
            else:
                receive_size = file_size
            chunk = f.read(receive_size)
            if chunk is None:
                raise ValueError(f"Failed to read chunk of {receive_size} bytes")
            crc32 = fastcrc.crc32.cd_rom_edc(chunk, crc32)
            file_size -= receive_size

    print(f"fast CRC32:{hex(crc32)}")

def test_crc(file_size):
    register = crc.TableBasedRegister(
        crc.Configuration(
            width=32,
            polynomial=0x8001801B,
            init_value=0x00000000,
            final_xor_value=0x00000000,
            reverse_input=True,
            reverse_output=True,
        )
    )

    register.init()

    with open('test.bin', 'rb') as f:
        while file_size:
            if file_size > MAX_BUFFER_SIZE:
                receive_size = MAX_BUFFER_SIZE
            else:
                receive_size = file_size
            chunk = f.read(receive_size)
            if chunk is None:
                raise ValueError(f"Failed to read chunk of {receive_size} bytes")
            register.update(chunk)
            file_size -= receive_size

    print(f"crc CRC32:{hex(register.digest())}")


def main():
    class Formatter(argparse.ArgumentDefaultsHelpFormatter, argparse.RawDescriptionHelpFormatter):
        pass

    parser = argparse.ArgumentParser(formatter_class=Formatter)

    parser.add_argument(
        "-l",
        "--size",
        type=int,
        default=MAX_FILE_SIZE,
        help="File size",
    )

    args = parser.parse_args()

    with open('test.bin', 'wb') as f:
        f.write(os.urandom(args.size))

    print(pt.time_benchmark(test_fastcrc, args.size, Number=1, Repeat=1)['raw_times'])
    print()
    print(pt.time_benchmark(test_crc, args.size, Number=1, Repeat=1)['raw_times'])


if __name__ == "__main__":
    sys.exit(main())
```

The differance is in ~1500 times.
```
./performance.py --size 1048576
fast CRC32:0x8f826ee2
[0.0021976690004521515]

crc CRC32:0x8f826ee2
[2.877936373999546]

./performance.py --size 2097152
fast CRC32:0xf7b9b7c8
[0.004301269000279717]

crc CRC32:0xf7b9b7c8
[5.8045584649989905]

 ./performance.py --size 20971520
fast CRC32:0xd0bd2570
[0.042839937003009254]

crc CRC32:0xd0bd2570
[56.61696475999997]

```
In case of [Register](https://nicoretti.github.io/crc/#__tabbed_5_1) performance more bad.

But your module have nice killer feature - custom [Configuration](https://nicoretti.github.io/crc/#__tabbed_1_2). Is it possible to reach better performance relatively close to fastcrc, say 2 or 3 times worse then the latter?

**Comment by mvkonovalov** [comment]
But your  module have nice killer feature `Configuration`. Is it possible to reach better performance relatively close to fastcrc, say 2 or 3 times worse then the latter?

**Comment by Nicoretti** [comment]
Hi @mvkonovalov ,

Thanks for reaching out. I understand your concerns about the performance.
Still top performance was never a primary design goal of this library. The core design goals have been:

* Zero Dependencies
* Pure Python
* Single File (so it can easily be vendored) 

Admittedly, I have slightly broken with the single file goal, but it can still be vendored today as a single file (for further details, see https://github.com/Nicoretti/crc/issues/110#issuecomment-1723353844 and following comments).

My personal take is that if **_performance is a key factor_** for someone, using [fastcrc](https://github.com/overcat/fastcrc) is the better choice.

In case you just require any CRC32 or exactly the one from zlib, using the built-in [zlib module](https://docs.python.org/3/library/zlib.html#zlib.crc32) is an option too.

Having said that, I understand if neither provides the configuration you need, you are "out of luck". However, as far as I know, fastcrc uses https://crates.io/crates/crc for calculating the checksums, which in turn also exposes an API for using custom configurations. Therefore, it would be interesting to get the perspective of the [fastcrc author](https://github.com/overcat) on whether they would be willing to expose that API. If they are open to it, I would even consider creating a PR (though likely not before the beginning of next year).

Hope that helps.

Best,  
Nico

**Comment by Nicoretti** [comment]
@mvkonovalov, I will close your issue in favor of https://github.com/Nicoretti/crc/issues/183. However, if you have further questions or discussion points, feel free to post in this issue.

Best,
Nico

**Comment by mvkonovalov** [comment]
> @mvkonovalov, I will close your issue in favor of #183. However, if you have further questions or discussion points, feel free to post in this issue.
> 
> Best, Nico

Thank you for the answer and new FAQ. 

Regards.
