### ISSUE TITLE
Automate all tasks necessary for a new release

### ISSUE THREAD

**Issue by Nicoretti** [Nicoretti/crc#24]
Create a script which takes care of release a new version

* bump version number
* add tag
* push to git
* ...

**Comment by cruisen** [comment]
Dear Nico, 
I use the CLI [poetry](https://python-poetry.org/) for all things python. And for bumping the version the [version command](https://python-poetry.org/docs/cli/#version).
Maybe you want to give it a try?

**Comment by Nicoretti** [comment]
Hi @cruisen ,

thx for the recommendation(s), I'll be looking into it when I can make some time during the holidays :)

best
Nico

**Comment by cruisen** [comment]
@Nicoretti any luck yet.

As mentioned, I use poetry. Here is my current Makefile. `make bump` will bump my version, build a wheel, tag, commit, push and upload to pypi.

See

**Comment by Nicoretti** [comment]
Hi @cruisen,

today I added a first basis of the automated releases, similar (inspired by your makefile) but instead of make I went with [nox](https://nox.thea.codes/en/stable/) which is somewhat platform independent.

best
Nico
